"""Initial migration (all models including shadow fields)

Revision ID: 14706d37507e
Revises: 
Create Date: 2026-01-09 00:43:33.253668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14706d37507e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('desired_version', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rollout_bucket', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('hardware_rev', sa.String(), nullable=True),
    sa.Column('reported_sample_interval_secs', sa.Integer(), nullable=True),
    sa.Column('reported_upload_interval_secs', sa.Integer(), nullable=True),
    sa.Column('reported_heartbeat_interval_secs', sa.Integer(), nullable=True),
    sa.Column('desired_sample_interval_secs', sa.Integer(), nullable=True),
    sa.Column('desired_upload_interval_secs', sa.Integer(), nullable=True),
    sa.Column('desired_heartbeat_interval_secs', sa.Integer(), nullable=True),
    sa.Column('desired_state', sa.String(), nullable=True),
    sa.Column('reported_state', sa.String(), nullable=True),
    sa.Column('config_flags', sa.String(), nullable=True),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_auth_token'), 'devices', ['auth_token'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('firmware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('rollout_group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rollout_phase', sa.String(), nullable=True),
    sa.Column('target_percent', sa.Integer(), nullable=True),
    sa.Column('required_region', sa.String(), nullable=True),
    sa.Column('required_hardware_rev', sa.String(), nullable=True),
    sa.Column('metrics_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_id'), 'firmware', ['id'], unique=False)
    op.create_index(op.f('ix_firmware_version'), 'firmware', ['version'], unique=True)
    op.create_table('fleet_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_devices', sa.Integer(), nullable=True),
    sa.Column('sample_interval_secs', sa.Integer(), nullable=True),
    sa.Column('upload_interval_secs', sa.Integer(), nullable=True),
    sa.Column('heartbeat_interval_secs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_settings_id'), 'fleet_settings', ['id'], unique=False)
    op.create_table('device_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_errors_id'), 'device_errors', ['id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_device_errors_id'), table_name='device_errors')
    op.drop_table('device_errors')
    op.drop_index(op.f('ix_fleet_settings_id'), table_name='fleet_settings')
    op.drop_table('fleet_settings')
    op.drop_index(op.f('ix_firmware_version'), table_name='firmware')
    op.drop_index(op.f('ix_firmware_id'), table_name='firmware')
    op.drop_table('firmware')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_auth_token'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
