"""add_segment_fields

Revision ID: 1e2914925222
Revises: ada577443c90
Create Date: 2026-01-08 23:40:44.369755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2914925222'
down_revision: Union[str, Sequence[str], None] = 'ada577443c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('region', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('hardware_rev', sa.String(), nullable=True))
    op.add_column('firmware', sa.Column('required_region', sa.String(), nullable=True))
    op.add_column('firmware', sa.Column('required_hardware_rev', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmware', 'required_hardware_rev')
    op.drop_column('firmware', 'required_region')
    op.drop_column('devices', 'hardware_rev')
    op.drop_column('devices', 'region')
    # ### end Alembic commands ###
