"""add_fleet_settings_table

Revision ID: 26e9b9db134f
Revises: 64fd386e3956
Create Date: 2026-01-08 21:50:57.532647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e9b9db134f'
down_revision: Union[str, Sequence[str], None] = '64fd386e3956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_devices', sa.Integer(), nullable=True),
    sa.Column('sample_interval_secs', sa.Integer(), nullable=True),
    sa.Column('upload_interval_secs', sa.Integer(), nullable=True),
    sa.Column('heartbeat_interval_secs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_settings_id'), 'fleet_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_settings_id'), table_name='fleet_settings')
    op.drop_table('fleet_settings')
    # ### end Alembic commands ###
