"""Update server_defaults for Device model

Revision ID: 28af5958361e
Revises: 2a3cba485576
Create Date: 2026-01-09 08:50:46.841845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28af5958361e'
down_revision: Union[str, Sequence[str], None] = '2a3cba485576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'predicted_issue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('predicted_issue', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
