"""Add rollout_status to Firmware model

Revision ID: 2a3cba485576
Revises: b9be5a18d8d6
Create Date: 2026-01-09 01:27:50.783598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3cba485576'
down_revision: Union[str, Sequence[str], None] = 'b9be5a18d8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmware', sa.Column('rollout_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmware', 'rollout_status')
    # ### end Alembic commands ###
