"""Add lifecycle_state, auth_token, registered_at to Device model

Revision ID: 2bea7bd3d8cf
Revises: 8b28e230b84d
Create Date: 2026-01-09 00:12:42.670618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bea7bd3d8cf'
down_revision: Union[str, Sequence[str], None] = '8b28e230b84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('lifecycle_state', sa.String(), nullable=True))
    op.execute("UPDATE devices SET lifecycle_state = 'new' WHERE lifecycle_state IS NULL")
    op.add_column('devices', sa.Column('auth_token', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_devices_auth_token'), 'devices', ['auth_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_auth_token'), table_name='devices')
    op.drop_column('devices', 'registered_at')
    op.drop_column('devices', 'auth_token')
    op.drop_column('devices', 'lifecycle_state')
    # ### end Alembic commands ###
