"""Add predicted_issue to Device model

Revision ID: 37497b8f08bf
Revises: 52929076803a
Create Date: 2026-01-09 00:54:40.385636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37497b8f08bf'
down_revision: Union[str, Sequence[str], None] = '52929076803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('predicted_issue', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'predicted_issue')
    # ### end Alembic commands ###
