"""Add metrics_summary to Firmware

Revision ID: 4435b818ff09
Revises: 1e2914925222
Create Date: 2026-01-08 23:58:57.654347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4435b818ff09'
down_revision: Union[str, Sequence[str], None] = '1e2914925222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmware', sa.Column('metrics_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmware', 'metrics_summary')
    # ### end Alembic commands ###
