"""add_environment_to_device

Revision ID: 47b0e0f113ac
Revises: e59fe03fc293
Create Date: 2026-01-08 23:17:41.566862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b0e0f113ac'
down_revision: Union[str, Sequence[str], None] = 'e59fe03fc293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('environment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'environment')
    # ### end Alembic commands ###
