"""Add sequence_number to Measurement

Revision ID: 64fd386e3956
Revises: 29b1e1cddd63
Create Date: 2026-01-08 18:59:18.491682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fd386e3956'
down_revision: Union[str, Sequence[str], None] = '29b1e1cddd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('sequence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'sequence_number')
    # ### end Alembic commands ###
