"""Add location and speed to Measurement model

Revision ID: 8b28e230b84d
Revises: baae1f92cf26
Create Date: 2026-01-09 00:03:46.514072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b28e230b84d'
down_revision: Union[str, Sequence[str], None] = 'baae1f92cf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'speed')
    op.drop_column('measurements', 'longitude')
    op.drop_column('measurements', 'latitude')
    # ### end Alembic commands ###
