"""Add firmware_version to Measurement model

Revision ID: 956e98956833
Revises: 4435b818ff09
Create Date: 2026-01-08 23:59:34.491705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956e98956833'
down_revision: Union[str, Sequence[str], None] = '4435b818ff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('firmware_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'firmware_version')
    # ### end Alembic commands ###
