"""Add signature to Firmware model

Revision ID: b9be5a18d8d6
Revises: 37497b8f08bf
Create Date: 2026-01-09 01:06:54.080536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9be5a18d8d6'
down_revision: Union[str, Sequence[str], None] = '37497b8f08bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmware', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmware', 'signature')
    # ### end Alembic commands ###
