"""Add config_flags to Device model

Revision ID: baae1f92cf26
Revises: 956e98956833
Create Date: 2026-01-09 00:01:37.485541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baae1f92cf26'
down_revision: Union[str, Sequence[str], None] = '956e98956833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('config_flags', sa.String(), nullable=True, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'config_flags')
    # ### end Alembic commands ###
