"""add_device_shadow_fields

Revision ID: d4f08505e8bd
Revises: 26e9b9db134f
Create Date: 2026-01-08 23:09:11.588204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f08505e8bd'
down_revision: Union[str, Sequence[str], None] = '26e9b9db134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('reported_sample_interval_secs', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('reported_upload_interval_secs', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('reported_heartbeat_interval_secs', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('desired_sample_interval_secs', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('desired_upload_interval_secs', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('desired_heartbeat_interval_secs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'desired_heartbeat_interval_secs')
    op.drop_column('devices', 'desired_upload_interval_secs')
    op.drop_column('devices', 'desired_sample_interval_secs')
    op.drop_column('devices', 'reported_heartbeat_interval_secs')
    op.drop_column('devices', 'reported_upload_interval_secs')
    op.drop_column('devices', 'reported_sample_interval_secs')
    # ### end Alembic commands ###
