"""add_rollout_fields

Revision ID: e59fe03fc293
Revises: d4f08505e8bd
Create Date: 2026-01-08 23:15:05.331299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59fe03fc293'
down_revision: Union[str, Sequence[str], None] = 'd4f08505e8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rollout_bucket', sa.Integer(), nullable=True))
    op.add_column('firmware', sa.Column('rollout_phase', sa.String(), nullable=True))
    op.add_column('firmware', sa.Column('target_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmware', 'target_percent')
    op.drop_column('firmware', 'rollout_phase')
    op.drop_column('devices', 'rollout_bucket')
    # ### end Alembic commands ###
